services:

  web:
    build: .
    container_name: azureops_web
    ports:
      - "8000:8000"
    environment:
      FLASK_ENV: development
      KEY_VAULT_URI: ""

  tests:
    build: .
    container_name: azureops_tests
    volumes:
      - ./:/workspace
    working_dir: /workspace
    environment:
      PYTHONPATH: /workspace/app:/workspace
    command: >
      sh -c "mkdir -p artifacts &&
      pytest tests/unit --maxfail=1 --disable-warnings -q --cov=app --cov-report=xml:artifacts/coverage/coverage.xml --cov-report=html:artifacts/coverage --junit-xml=artifacts/unit_result.xml &&
      pytest tests/integration --maxfail=1 --disable-warnings -q --cov=app --cov-append --cov-report=xml:artifacts/coverage/coverage.xml --cov-report=html:artifacts/coverage --junit-xml=artifacts/integration_result.xml &&
      junit2html artifacts/unit_result.xml artifacts/unit_result.html &&
      junit2html artifacts/integration_result.xml artifacts/integration_result.html"

