---
- name: Configurar App Service en Azure
  hosts: localhost
  connection: local
  vars:
    resource_group: "{{ lookup('env','RESOURCE_GROUP_NAME') }}"
    app_name:      "{{ lookup('env','APP_NAME') }}"
    vault_name:    "{{ lookup('env','KEY_VAULT_NAME') }}"
    tenant_id:     "{{ lookup('env','AZURE_TENANT_ID') }}"
    subscription_id:     "{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}"
  tasks:
    - name: Habilitar logging de diagnóstico HTTP
      azure_rm_appserviceadvancedapideployment:
        resource_group: "{{ resource_group }}"
        name:           "{{ app_name }}"
        site_config:
          http_logging_enabled:          true
          detailed_error_logging_enabled: true

    - name: Obtener detalles de la App Service
      azure_rm_webapp_info:
        resource_group: "{{ resource_group }}"
        name:           "{{ app_name }}"
      register: app_info

    - name: Asignar rol 'Key Vault Secrets User' si falta
      azure_rm_keyvaultaccesspolicy:
        resource_group: "{{ resource_group }}"
        vault_name:    "{{ vault_name }}"
        tenant_id:     "{{ tenant_id }}"
        object_id:     "{{ app_info.webapp.identity.principal_id }}"
        secret_permissions:
          - get
          - list

    - name: Verificar asignación de rol Key Vault Secrets User
      azure_rm_roleassignment_info:
        scope: "/subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group }}"
        role_definition_name: "Key Vault Secrets User"
      register: assignments

    - name: Mostrar asignaciones de rol para Key Vault
      debug:
        var: assignments.assignments
